services:
  postgres:
    image: postgres:15
    container_name: video_resume_pg
    environment:
      POSTGRES_DB: video_resume_ai
      POSTGRES_USER: video_resume
      POSTGRES_PASSWORD: video_resume
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: video_resume_redis
    ports:
      - "6380:6379"

volumes:
  pg_data:
